@echo off
echo Starting Anki Viewer...
echo 1. Opening Browser...
start http://localhost:8000
echo 2. Starting Local Server...
echo (Keep this window open while using the app)
python -m http.server 8000
